# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "user_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import user_pb2 as user__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12user_service.proto\x12\x0cuser_service\x1a\nuser.proto"A\n\x1d\x41uthenticateWithGoogleRequest\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user.UserMetadata"O\n\x1e\x41uthenticateWithGoogleResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\x12\x13\n\x0bis_new_user\x18\x02 \x01(\x08"&\n\x15GetUserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t"%\n\x12\x43reateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08""\n\x11\x44\x65leteUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xca\x02\n\x0bUserService\x12s\n\x16\x41uthenticateWithGoogle\x12+.user_service.AuthenticateWithGoogleRequest\x1a,.user_service.AuthenticateWithGoogleResponse\x12\x41\n\x0eGetUserByEmail\x12#.user_service.GetUserByEmailRequest\x1a\n.user.User\x12\x36\n\x06\x43reate\x12\n.user.User\x1a .user_service.CreateUserResponse\x12K\n\x06\x44\x65lete\x12\x1f.user_service.DeleteUserRequest\x1a .user_service.DeleteUserResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUTHENTICATEWITHGOOGLEREQUEST"]._serialized_start = 48
    _globals["_AUTHENTICATEWITHGOOGLEREQUEST"]._serialized_end = 113
    _globals["_AUTHENTICATEWITHGOOGLERESPONSE"]._serialized_start = 115
    _globals["_AUTHENTICATEWITHGOOGLERESPONSE"]._serialized_end = 194
    _globals["_GETUSERBYEMAILREQUEST"]._serialized_start = 196
    _globals["_GETUSERBYEMAILREQUEST"]._serialized_end = 234
    _globals["_CREATEUSERRESPONSE"]._serialized_start = 236
    _globals["_CREATEUSERRESPONSE"]._serialized_end = 273
    _globals["_DELETEUSERREQUEST"]._serialized_start = 275
    _globals["_DELETEUSERREQUEST"]._serialized_end = 309
    _globals["_DELETEUSERRESPONSE"]._serialized_start = 311
    _globals["_DELETEUSERRESPONSE"]._serialized_end = 348
    _globals["_USERSERVICE"]._serialized_start = 351
    _globals["_USERSERVICE"]._serialized_end = 681
# @@protoc_insertion_point(module_scope)
